version: '3'

tasks:

  lint:
    desc: Check code quality
    cmds:
      - uv run ruff check . --fix

  format:
    desc: Format code
    cmds:
      - uv run ruff format .

  seasonality:
    desc: Run seasonality analysis (default 5 years)
    cmds:
      - uv run python main.py seasonality --years {{.YEARS | default 5}}

  valuation-ts:
    desc: Time series valuation analysis
    cmds:
      - uv run python main.py valuation-ts --years {{.YEARS | default 10}} --risk-premium {{.PREMIUM | default 3.5}}