version: '3'

tasks:
  setup:
    desc: Install dependencies
    cmds:
      - uv sync

  test:
    desc: Run tests
    cmds:
      - uv run pytest

  lint:
    desc: Check code quality
    cmds:
      - uv run ruff check . --fix

  format:
    desc: Format code
    cmds:
      - uv run ruff format .

  validate:
    desc: Run all checks (format, lint, test)
    deps: [format, lint, test]

  valuation:
    desc: Run market valuation analysis
    cmds:
      - uv run python main.py valuation --current-per {{.PER | default 16.0}} --jgb-yield {{.YIELD | default 1.0}} --risk-premium {{.PREMIUM | default 3.5}}

  seasonality:
    desc: Run seasonality analysis (default 5 years)
    cmds:
      - uv run python main.py seasonality --years {{.YEARS | default 5}}

  valuation-ts:
    desc: Time series valuation analysis
    cmds:
      - uv run python main.py valuation-ts --years {{.YEARS | default 10}} --jgb-yield {{.YIELD | default 3.5}} --risk-premium {{.PREMIUM | default 3.5}}